[package]
edition = "2021"
name = "verusbot"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.26", features = ["rkyv"] }
color-eyre = "0.6.2"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "1.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "net"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
    "std",
    "json",
] }
tracing-appender = "0.2.2"
uuid = { version = "1.4", features = ["v4"] }
vrsc = "0.0.1"
# vrsc-rpc = { path = "../rust-vrsc-rpc/client" } # "0.1.8"
vrsc-rpc = "0.1.15"

futures = "0.3"
poise = { features = ["cache"], version = "0.5.0" }
fast_qr = { version = "0.9.0", features = ["image"] }
fancy-regex = "0.11.0"
num-traits = "0.2.15"
reqwest = { version = "0.11.19", features = ["json"] }
emojis = "0.6"

[dependencies.sqlx]
default-features = false
features = [
    "postgres",
    "macros",
    "bigdecimal",
    "migrate",
    "uuid",
    "chrono",
    "runtime-tokio-rustls",
]
version = "0.7.1"
