version: '3.7'
services:
  verusbot:
    container_name: verusbot
    image: verusbot
    build:
      context: .
    restart: "no"
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - '.env:/.env:ro'
      - /tmp/discord_bot_block_vrsctest.sock:/tmp/discord_bot_block_vrsctest.sock
    network_mode: "host"
    depends_on:
      - postgres
      - jaeger
  postgres:
    container_name: postgres
    image: 'postgres:alpine'
    restart: "no"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD?:REQUIRED}"
      POSTGRES_USER: "${POSTGRES_USER?:REQUIRED}"
      POSTGRES_DB: "${POSTGRES_DB?:REQUIRED}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
volumes:
  postgres-data:
